# Navigation Links
# The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Technical Notes
    url: docs/
    weight: 20
  - name: Videos
    url: /videos/
    weight: 30
    
# Sidebar for the documentation pages
sidebar:
  - identifier: social_header
    name: Connect
    params:
      type: separator
    weight: 10
  - identifier: youtube_sidebar
    name: "YouTube Channel"
    url: "https://www.youtube.com/@DominalaFisica"
    weight: 20
  - identifier: instagram_sidebar
    name: "Instagram"
    url: "https://www.instagram.com/dominalafisica"
    weight: 30
